modLoader = "javafml"
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/YukkuriC/HexParseMod/issues"
license = "MIT"

[[mods]]
modId = "hexparse"
version = "${version}"
displayName = "HexParse"
authors = "YukkuriC"
description = '''
parse pattern registry name code into list iota, and vice versa
'''
logoFile = "logo.png"
updateJSONURL = "https://api.modrinth.com/updates/WjFyIzFj/forge_updates.json"
displayURL = "https://modrinth.com/mod/hexparse"

[[mixins]]
config = "hexparse.mixins.json"
[[mixins]]
config = "hexparse.mixins.tmp_patches.json"

[[dependencies.hexparse]]
modId = "minecraft"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexparse]]
modId = "hexcasting"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexparse]]
modId = "hexal"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexparse]]
modId = "moreiotas"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
